swagger: '2.0'

info:
  version: 1.0.0
  title: Coopaer API

servers:
  - url: http://localhost:3000/api/v1

tags:
  - name: 'Acesso'
    description: 'Registro, login e logout'
  - name: 'Cooperado'
    description: 'Dados dos cooperados'

paths:
  /admin/login:
    post:
      summary: Realiza o login do usuário.
      tags:
        - 'Acesso'
      description: Autentica o usuário com base no e-mail e senha fornecidos. O token da sessão de usuário (Authorization) é informado no response headers da requisição.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: admin
          description: Credenciais do usuário para login.
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        200:
          description: Usuário autenticado com sucesso.
          schema:
            $ref: '#/definitions/LoginResponse'
        401:
          description: E-mail ou senha inválidos.
          schema:
            $ref: '#/definitions/InvalidCredentialsResponse'
  /admin/logout:
    delete:
      summary: Realiza o logout do usuário.
      tags:
        - 'Acesso'
      description: Encerra a sessão do usuário.
      produces:
        - application/json
      security:
        - BearerAuth: []
      responses:
        200:
          description: Usuário saiu com sucesso.
          schema:
            $ref: '#/definitions/LogoutSuccessResponse'
        401:
          description: Não foi possível encontrar uma autenticação.
          schema:
            $ref: '#/definitions/LogoutErrorResponse'

  /member/login:
    post:
      summary: Realiza o login do Cooperado.
      tags:
        - 'Acesso'
      description: Autentica o cooperado com base no e-mail e senha fornecidos. O token da sessão de usuário (Authorization) é informado no response headers da requisição.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: member
          description: Credenciais do cooperado para login.
          required: true
          schema:
            $ref: '#/definitions/LoginMemberRequest'
      responses:
        200:
          description: Cooperado autenticado com sucesso.
          schema:
            $ref: '#/definitions/LoginResponse'
        401:
          description: E-mail ou senha inválidos.
          schema:
            $ref: '#/definitions/InvalidCredentialsResponse'
  /member/logout:
    delete:
      summary: Realiza o logout do cooperado.
      tags:
        - 'Acesso'
      description: Encerra a sessão do cooperado.
      produces:
        - application/json
      security:
        - BearerAuth: []
      responses:
        200:
          description: Cooperado saiu com sucesso.
          schema:
            $ref: '#/definitions/LogoutSuccessResponse'
        401:
          description: Não foi possível encontrar uma autenticação.
          schema:
            $ref: '#/definitions/LogoutErrorResponse'

  /api/v1/profile_members:
    get:
      summary: Obtém o perfil de um membro específico.
      tags:
        - 'Cooperado'
      description: Retorna as informações do perfil de um membro com base no ID fornecido.
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          description: Número da página a ser recuperada.
          required: false
          type: integer
          default: 1
      responses:
        200:
          description: Perfil do membro recuperado com sucesso.
          schema:
            $ref: '#/definitions/MemberProfileResponse'
        404:
          description: Perfil do membro não encontrado.
          schema:
            $ref: '#/definitions/NotFoundResponse'
    post:
      summary: Cria um novo perfil de membro
      tags:
        - 'Cooperado'
      description: Cria um novo perfil de membro com base nos dados fornecidos.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          description: Dados do cooperado a sere criado.
          required: true
          schema:
            $ref: '#/definitions/NewMemberProfileRequest'
      responses:
        '200':
          description: Perfil do membro criado com sucesso.
        '401':
          description: Não autorizado
        '400':
          description: Dados inválidos

definitions:
  LoginRequest:
    type: object
    properties:
      admin:
        type: object
        properties:
          email:
            type: string
            example: "admin@admin.com"
          password:
            type: string
            example: "123456"
  LoginResponse:
    type: object
    properties:
      status:
        type: object
        properties:
          code:
            type: integer
            example: 200
          message:
            type: string
            example: "Autenticado com sucesso"
          data:
            type: object
            properties:
              admin:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  email:
                    type: string
                    example: "jemison321@gmail.com"
                  name:
                    type: string
                    example: "Jemison"
  InvalidCredentialsResponse:
    type: object
    properties:
      status:
        type: object
        properties:
          code:
            type: integer
            example: 401
          message:
            type: string
            example: "Invalid Email or password"

  LoginMemberRequest:
    type: object
    properties:
      member:
        type: object
        properties:
          email:
            type: string
            example: "member@member.com"
          password:
            type: string
            example: "123456"

  LogoutSuccessResponse:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: "Saiu com sucesso"
  LogoutErrorResponse:
    type: object
    properties:
      status:
        type: integer
        example: 401
      message:
        type: string
        example: "Não foi possível encontrar uma autenticação"

  MemberProfileResponse:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              example: "25"
            type:
              type: string
              example: "profile_member"
            attributes:
              type: object
              properties:
                name:
                  type: string
                  example: "Laverne O'Connell Sr."
                cell_phone:
                  type: string
                  example: "979-728-6895"
                phone:
                  type: string
                  example: "586-007-7671 x634"
                birth:
                  type: string
                  example: "2005-02-21"
                cpf:
                  type: string
                  example: "10778423411"
                rg:
                  type: string
                  example: "188126739"
                gender:
                  type: string
                  example: "female"
                marital_status:
                  type: string
                  example: "viúvo"
                pis:
                  type: string
                  example: "14459521948"
                expedition:
                  type: string
                  example: "North Eleonor"
                mother_name:
                  type: string
                  example: "Otha Tromp"
                father_name:
                  type: string
                  example: "Ebonie Feest"
                municipal_registration:
                  type: string
                  example: "11794469"
                city_registration:
                  type: string
                  example: "29704263"
                member:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 25
                    email:
                      type: string
                      example: "paul.okon@willms-friesen.test"
                    created_at:
                      type: string
                      example: "2024-03-08T04:56:56.322Z"
                    updated_at:
                      type: string
                      example: "2024-03-08T04:56:56.322Z"
                academic_educationals:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 49
                      degree:
                        type: string
                        example: "Bachelor of Nursing"
                      course:
                        type: string
                        example: "Bachelor of Criminology"
                      number_register:
                        type: string
                        example: "17714943"
                      profile_member_id:
                        type: integer
                        example: 25
                      created_at:
                        type: string
                        example: "2024-03-08T04:56:56.333Z"
                      updated_at:
                        type: string
                        example: "2024-03-08T04:56:56.333Z"
                address:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 25
                    street:
                      type: string
                      example: "Kovacek Fields"
                    number:
                      type: integer
                      example: 77846
                    neighborhood:
                      type: string
                      example: "Summer Pointe"
                    city:
                      type: string
                      example: "West Normaborough"
                    uf:
                      type: string
                      example: "NC"
                    mailing:
                      type: string
                      example: "f"
                    email_mailing:
                      type: string
                      example: "bryant_crist@powlowski.test"
                    profile_member_id:
                      type: integer
                      example: 25
                    created_at:
                      type: string
                      example: "2024-03-08T04:56:56.338Z"
                    updated_at:
                      type: string
                      example: "2024-03-08T04:56:56.338Z"
                bank_account:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 25
                    account:
                      type: string
                      example: "2661460018"
                    agency:
                      type: string
                      example: "242641052"
                    bank:
                      type: string
                      example: "ALLIED BANK PHILIPPINES (UK) PLC"
                    account_type:
                      type: string
                      example: "435"
                    pix:
                      type: string
                      example: "95999207500"
                    profile_member_id:
                      type: integer
                      example: 25
                    created_at:
                      type: string
                      example: "2024-03-08T04:56:56.341Z"
                    updated_at:
                      type: string
                      example: "2024-03-08T04:56:56.341Z"
                dependents:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 49
                      name:
                        type: string
                        example: "Michel Stokes"
                      birth:
                        type: string
                        example: "2021-01-20"
                      profile_member_id:
                        type: integer
                        example: 25
                      created_at:
                        type: string
                        example: "2024-03-08T04:56:56.343Z"
                      updated_at:
                        type: string
                        example: "2024-03-08T04:56:56.343Z"
      meta:
        type: object
        properties:
          total_count:
            type: integer
            example: 25
          total_pages:
            type: integer
            example: 3
          current_page:
            type: integer
            example: 1
          per_page:
            type: integer
            example: 10
  NewMemberProfileRequest:
      type: object
      properties:
        name:
          type: string
          example: "Laverne O'Connell Sr."
        cell_phone:
          type: string
          example: "979-728-6895"
        phone:
          type: string
          example: "586-007-7671 x634"
        birth:
          type: string
          format: date
          example: "2005-02-21"
        cpf:
          type: string
          example: "10778423411"
        rg:
          type: string
          example: "188126739"
        gender:
          type: string
          example: "female"
        marital_status:
          type: string
          example: "viúvo"
        pis:
          type: string
          example: "14459521948"
        expedition:
          type: string
          example: "North Eleonor"
        mother_name:
          type: string
          example: "Otha Tromp"
        father_name:
          type: string
          example: "Ebonie Feest"
        municipal_registration:
          type: string
          example: "11794469"
        city_registration:
          type: string
          example: "29704263"
        member_attributes:
          type: object
          properties:
            email:
              type: string
              example: "paul.okon@willms-friesen.test"
        academic_educationals_attributes:
          type: array
          items:
            type: object
            properties:
              degree:
                type: string
                example: "Bachelor of Nursing"
              course:
                type: string
                example: "Bachelor of Criminology"
              number_register:
                type: string
                example: "17714943"
              profile_member_id:
                type: integer
                example: 25
        addresses_attributes:
          type: object
          properties:
            street:
              type: string
              example: "Kovacek Fields"
            number:
              type: integer
              example: 77846
            neighborhood:
              type: string
              example: "Summer Pointe"
            city:
              type: string
              example: "West Normaborough"
            uf:
              type: string
              example: "NC"
            mailing:
              type: string
              example: "f"
            email_mailing:
              type: string
              example: "bryant_crist@powlowski.test"
            profile_member_id:
              type: integer
              example: 25
        bank_accounts_attributes:
          type: object
          properties:
            account:
              type: string
              example: "2661460018"
            agency:
              type: string
              example: "242641052"
            bank:
              type: string
              example: "ALLIED BANK PHILIPPINES (UK) PLC"
            account_type:
              type: string
              example: "435"
            pix:
              type: string
              example: "95999207500"
            profile_member_id:
              type: integer
              example: 25
        dependents_attributes:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: "Michel Stokes"
              birth:
                type: string
                format: date
                example: "2021-01-20"
              profile_member_id:
                type: integer
                example: 25

  NotFoundResponse:
    type: object
    properties:
      error:
        type: string
        example: "Não encontrado."

securityDefinitions:
    BearerAuth:
      type: apiKey
      in: header
      name: Authorization
